//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.08.22 at 12:34:47 PM GMT+01:00 
//


package net.keren.keren;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.keren.net/keren}navigationcase" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="fromviewid" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "navigationcase"
})
@XmlRootElement(name = "navigationrule")
public class Navigationrule {

    protected List<Navigationcase> navigationcase;
    @XmlAttribute(name = "fromviewid")
    protected String fromviewid;

    /**
     * Gets the value of the navigationcase property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the navigationcase property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNavigationcase().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Navigationcase }
     * 
     * 
     */
    public List<Navigationcase> getNavigationcase() {
        if (navigationcase == null) {
            navigationcase = new ArrayList<Navigationcase>();
        }
        return this.navigationcase;
    }

    /**
     * Gets the value of the fromviewid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFromviewid() {
        return fromviewid;
    }

    /**
     * Sets the value of the fromviewid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFromviewid(String value) {
        this.fromviewid = value;
    }

}
